
#ifndef RESOURCE_OP_H
#define RESOURCE_OP_H

enum ResourceOp {
    RES_OP_NONE,
    RES_OP_SHUTDOWN,
    RES_OP_ZONE_REQUEST,
    RES_OP_ZONE_TYPE_WLD,
    RES_OP_ZONE_TYPE_EQG,
    RES_OP_ZONE_TYPE_NOT_FOUND,
    RES_OP_ZONE_LOAD_PROGRESS,
};

#endif/*RESOURCE_OP_H*/
