
#ifndef ZEQ_EXPANSION_H
#define ZEQ_EXPANSION_H

enum ZeqExpansionId {
    ZEQ_EXPANSION_TRILOGY,
    ZEQ_EXPANSION_TITANIUM,
    ZEQ_EXPANSION_COUNT
};

enum ZeqExpansionLegacyId {
    ZEQ_EXPANSION_LEGACY_TRILOGY,
    ZEQ_EXPANSION_LEGACY_COUNT
};

enum ZeqExpansionModernId {
    ZEQ_EXPANSION_MODERN_TITANIUM,
    ZEQ_EXPANSION_MODERN_COUNT
};

#define ZEQ_EXPANSION_TRILOGY_BIT (1 << ZEQ_EXPANSION_TRILOGY)
#define ZEQ_EXPANSION_TITANIUM_BIT (1 << ZEQ_EXPANSION_TITANIUM)

#endif/*ZEQ_EXPANSION_H*/
